### ISSUE TITLE
How can I do it in a dynamic way and with other locations?

### ISSUE THREAD

**Issue by Carlosferrerhernandez** [maoberlehner/using-the-google-maps-api-with-vue#2]

**Comment by maoberlehner** [comment]
Hello @Carlosferrerhernandez 

this article is about how to integrate Google Maps into Vue.js - everything regarding how to work with Google Maps itself isn't any different to how to use Google Maps without Vue.js. So I'd recommend you to take a look into the official Google Maps documentation: https://developers.google.com/maps/documentation/javascript/tutorial
Thx!
